###
GET http://localhost:3000/books

###
GET http://localhost:3000/books/67a88777fa9f0f6e71d68367

###
POST http://localhost:3000/books
Content-Type: application/json

{
    "title": "nota kaki"
}

###
PATCH  http://localhost:3000/books/67a88777fa9f0f6e71d68367
Content-Type: application/json

{
    "title": "John Wicked"
}

###

DELETE  http://localhost:3000/books/67a827f728e12838f656a399