###
GET http://localhost:3000/notes

###
GET http://localhost:3000/notes/67a5b70450df19d064ab2e98

###
POST http://localhost:3000/notes
Content-Type: application/json

{
    "title": "nota kaki"
}

###
PATCH  http://localhost:3000/notes/67a827f728e12838f656a399
Content-Type: application/json

{
    "title": "John Wicked"
}

###

DELETE  http://localhost:3000/notes/67a827f728e12838f656a399