###
GET http://localhost:3000/notes

###
GET http://localhost:3000/notes/679c0baa9301128095343c05

###
POST http://localhost:3000/notes
Content-Type: application/json

{
    "title": "nota kaki"
}

###
PATCH  http://localhost:3000/users/679c11035f6a07b6a0de0183
Content-Type: application/json

{
    "name": "John Wicked"
}

###

DELETE  http://localhost:3000/users/679c0baa9301128095343c05